<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>managereserve01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dd5023c4-fc6d-445b-944f-0ebb80d3fe0f</testSuiteGuid>
   <testCaseLink>
      <guid>6e977bc0-cd98-43bc-87de-40f3a1fc403f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/login01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c48c2bb4-c496-4047-97f8-6e5148aedcb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8246840d-1186-4bdd-b6df-892220e1cbf4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3320eece-7423-4164-a256-e61a2bfaacb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/managereserve/managereserve01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4f375742-6966-4ab6-83f4-57201ac71b23</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/reserve</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4f375742-6966-4ab6-83f4-57201ac71b23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fecha</value>
         <variableId>9e621bca-12ab-494c-9c56-d138d80155eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4f375742-6966-4ab6-83f4-57201ac71b23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>restaurante</value>
         <variableId>bce08a92-5361-41ac-938c-7291fb75f430</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4f375742-6966-4ab6-83f4-57201ac71b23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>mesa</value>
         <variableId>3ac9c6fc-4659-49fa-acf1-770f130f1d8f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
