<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneOrder 1 - Capacity 1Order 2 - Capacity 2Order 3 - Capacity 3Order 4 - Capacity 4 (1)</name>
   <tag></tag>
   <elementGuidId>f0797da1-52d3-496c-b31a-1c00b028365e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tableId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6efe0faa-82ee-4c71-b77f-1e59a05b3736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>de0d5a5d-2906-48e5-9778-73f5de3329b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>f28f81a9-4bc0-4d29-b8e2-f02ab8de950a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>8f0be2ea-6c78-4dca-b366-0d1c11884e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4</value>
      <webElementGuid>760f9887-527e-4157-9295-e7c12d0308e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableId&quot;)</value>
      <webElementGuid>bef872c8-737b-4c19-8ce2-1f9dbe68fb17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tableId']</value>
      <webElementGuid>7c293ef9-940b-4d16-9e6b-724ec6f3771e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>7eeab02d-8895-4f3f-9ed8-2019e9b921ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tableId' and @id = 'tableId' and (text() = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4' or . = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4')]</value>
      <webElementGuid>c6e1c7e1-23e2-4c25-a4ca-b9472f16feab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
