<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneOrder 1 - Capacity 1Order 2 - Capacity 2Order 3 - Capacity 3Order 4 - Capacity 4</name>
   <tag></tag>
   <elementGuidId>a1023019-4144-48b9-8c6f-550d7ea0f34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tableId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6fd13d49-86de-4bd1-96f3-fa7d846c6d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>f1babd19-316c-4ea6-86de-e7d06880e93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>1e0d780f-e45b-4600-8b54-296d0d3dae04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>fc96f227-8207-4657-9e55-6a622dabaa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4</value>
      <webElementGuid>b74ece90-0a95-494d-a794-cd0dbf171468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableId&quot;)</value>
      <webElementGuid>04cda52d-0578-494b-9ce2-83a088ef4e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tableId']</value>
      <webElementGuid>ad1b0a38-31c6-4b40-a5e7-6f8b58b6c83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>1359ec09-b850-4217-88f7-ad883dd1e7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tableId' and @id = 'tableId' and (text() = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4' or . = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4')]</value>
      <webElementGuid>d823dfab-741a-49cd-9d5c-5bda5bc47065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
