<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneMilano</name>
   <tag></tag>
   <elementGuidId>40560ab5-e27c-47b6-944c-53931f071a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#restaurantId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='restaurantId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>441c34c0-3d13-46d9-be23-6e7f419b0537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>1442e26e-0e7f-4a45-9770-67b924911de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>e06b11fe-c1a9-47e3-bbc4-fb18e6535a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>a84465cf-cd2e-448c-8a46-f5ce7b363e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneMilano</value>
      <webElementGuid>a49b1a49-1dc5-46f8-b686-60215b1b90ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restaurantId&quot;)</value>
      <webElementGuid>d27e977f-6231-4e69-a53c-59e933d633d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='restaurantId']</value>
      <webElementGuid>be8c809d-fbbd-46e5-9819-5f6536e08a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2cb31e88-5506-4d70-b509-a3ffda49328e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'restaurantId' and @id = 'restaurantId' and (text() = 'Select OneMilano' or . = 'Select OneMilano')]</value>
      <webElementGuid>c84d24e0-aebb-4e39-a53f-7c4bd16c2415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
