<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneMilano (1)</name>
   <tag></tag>
   <elementGuidId>f3bab9d0-2cda-4d65-8f50-ffca127ba67c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#restaurantId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='restaurantId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9159a11-ae6e-4b89-a929-d192567df835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>e2790000-fe10-4baa-8028-03c26559d093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>2ce5694c-792f-4157-a15c-7cac56dedee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>8c0fef20-1e48-41a9-a656-961c0772013b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneMilano</value>
      <webElementGuid>f1be09a5-b6a3-4ae8-9cf9-3d77ed44bb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restaurantId&quot;)</value>
      <webElementGuid>4030a358-f26a-4c55-9702-bf05d4ee6262</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='restaurantId']</value>
      <webElementGuid>cfbe7de8-2c27-420f-aadf-8f83a7dcbeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>49585e2a-5644-49ec-b2fb-dd0e59c87891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'restaurantId' and @id = 'restaurantId' and (text() = 'Select OneMilano' or . = 'Select OneMilano')]</value>
      <webElementGuid>23e642a8-20a7-4756-9df3-3cbe0101af8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
