<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign Up</name>
   <tag></tag>
   <elementGuidId>05673fd7-3909-476c-8f9c-1122bd49135f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Sign Up')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be0cdac5-c08d-40ce-bb00-15da829c97bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>855dab6b-fc68-4b48-976f-06b0d767536b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>auth/signup</value>
      <webElementGuid>431ec376-10de-4afd-80eb-9efcbc94d27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>4642c99c-d153-46a3-a661-3f4041ab2333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_5f06f5&quot;]/div[@class=&quot;bg-violet-950 h-screen relative text-white&quot;]/nav[@class=&quot;gap-8 font-[400] absolute top-12 right-48&quot;]/a[@class=&quot;link&quot;]</value>
      <webElementGuid>7b852fb0-fddb-48b1-9b46-0611ad656b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign Up')]</value>
      <webElementGuid>ccb4a6d9-c18f-45e6-a6fa-84bf4ee5f5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'auth/signup')]</value>
      <webElementGuid>06c2cf45-81ab-4014-9ea9-f1968f1ffa9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>9ebee49b-486c-4a0f-aa27-87b245876786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'auth/signup' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>d19b2788-ba23-430f-a400-4f2b6315ef67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
