<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CANCEL</name>
   <tag></tag>
   <elementGuidId>0975f3e7-0980-4f8b-93d2-8e5584304bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.bg-red-600.text-white.text-xs.py-1.px-6.rounded-md.tracking-wide</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f98f1cb-36da-477a-8d6a-6b48008b5ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-red-600 text-white text-xs py-1 px-6 rounded-md tracking-wide</value>
      <webElementGuid>374202bb-23fd-4486-be0a-8b645b460f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>bd9899ff-09ad-4c84-8ada-a5f0be8d6ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_5f06f5&quot;]/div[@class=&quot;relative h-screen&quot;]/main[@class=&quot;px-16&quot;]/div[@class=&quot;mt-8&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;bg-violet-300 rounded-xl pl-6  mt-6&quot;]/div[@class=&quot;bg-zinc-50 rounded-xl shadow-md p-4 flex flex-col gap-6 relative&quot;]/div[@class=&quot;flex gap-3 justify-between&quot;]/div[@class=&quot;w-2/6 flex self-end justify-end gap-3&quot;]/button[@class=&quot;bg-red-600 text-white text-xs py-1 px-6 rounded-md tracking-wide&quot;]</value>
      <webElementGuid>8b9571bd-878c-4fb6-816d-24a1d1fad16e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>97fffa8e-e4de-4c3e-982d-3da906de7b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>a50d5138-04bc-4a7b-9141-c19769a8db64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
