<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneMilano</name>
   <tag></tag>
   <elementGuidId>f224f6ee-b826-4f1d-b425-3a6eff4ea39c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='restaurantId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#restaurantId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3452e1eb-f633-441f-9834-948bb2e5c15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>b1ae570f-b56d-42da-ab8d-fe089a82d5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>7f8128c8-c3a0-4194-8f5b-8acd29353577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>3ec2743c-53d9-4e45-a89f-0b942124ffa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneMilano</value>
      <webElementGuid>c7f91da8-baab-4866-af39-05552d776801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restaurantId&quot;)</value>
      <webElementGuid>2b33be31-d673-4784-a051-d40009e528c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='restaurantId']</value>
      <webElementGuid>e7469f62-fe50-443a-9121-5577273a528a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>42823a33-5a96-4c19-a3ea-6bcb8ca11f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'restaurantId' and @id = 'restaurantId' and (text() = 'Select OneMilano' or . = 'Select OneMilano')]</value>
      <webElementGuid>64bcabfc-feba-401d-b9fd-fa0b73aec37b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
