<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneOrder 1 - Capacity 1Order _9c6b5b</name>
   <tag></tag>
   <elementGuidId>277c9324-8be1-434d-bdf2-29526eb608bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tableId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tableId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fafeade5-8b84-4e5f-9f90-e86210a6cc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>9222f240-6b87-4ccf-b8ca-1a147e595103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>20d87ee1-e4a5-44df-89df-57b37de03061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>b3654993-235b-4497-ab97-31af786a4488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4</value>
      <webElementGuid>1c261420-523c-478c-9221-e0477691acb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableId&quot;)</value>
      <webElementGuid>b290339d-b4d1-492c-a2bc-ac8b7b0aef76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tableId']</value>
      <webElementGuid>b9e2b4aa-84f0-40c8-845b-77ab6ba5e7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>956166a7-647b-4b1e-98fa-abbdec25f707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tableId' and @id = 'tableId' and (text() = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4' or . = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4')]</value>
      <webElementGuid>54ec9b9e-63b4-4e9a-acb8-2b94802e491f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
