<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Reservation</name>
   <tag></tag>
   <elementGuidId>7e3909e3-5104-4448-aeb8-868393e17753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Add Reservation')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c0919e3-b66e-49b2-8a04-c88b0cf98c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>844c4411-f3e8-4c8a-890c-1c195e7908db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home/reservation/new</value>
      <webElementGuid>9fe4cc14-c42e-4a99-84df-902525ca7480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Reservation</value>
      <webElementGuid>05b18500-0c15-48c1-b379-cae66bd563a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_5f06f5&quot;]/div[@class=&quot;relative h-screen&quot;]/div[@class=&quot;flex items-center bg-violet-950 justify-between px-10 text-white py-3&quot;]/div[@class=&quot;flex w-[70%] font-[400] gap-16&quot;]/a[@class=&quot;link&quot;]</value>
      <webElementGuid>c3841195-125e-4f75-aaf0-b163a47b1970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Reservation')]</value>
      <webElementGuid>cb88e880-ff9e-491e-afa1-70fd0ffb0c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/home/reservation/new')]</value>
      <webElementGuid>140ac53d-cb91-4b16-86fd-e15ffb18f729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>9fa62056-b54f-408a-a390-a755e1bf455d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home/reservation/new' and (text() = 'Add Reservation' or . = 'Add Reservation')]</value>
      <webElementGuid>b9313014-9dd1-4db4-8c0a-e0918f5af185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
