<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CANCEL</name>
   <tag></tag>
   <elementGuidId>0975f3e7-0980-4f8b-93d2-8e5584304bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.bg-red-600.text-white.text-xs.py-1.px-6.rounded-md.tracking-wide</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc3c7d27-3ece-476c-8c4e-4b4472263df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-red-600 text-white text-xs py-1 px-6 rounded-md tracking-wide</value>
      <webElementGuid>52e7e7e6-8216-442e-8552-55e63bf0a40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>c8b63e60-9054-4228-a774-8f9f12cb232b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_5f06f5&quot;]/div[@class=&quot;relative h-screen&quot;]/main[@class=&quot;px-16&quot;]/div[@class=&quot;mt-8&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;bg-violet-300 rounded-xl pl-6  mt-6&quot;]/div[@class=&quot;bg-zinc-50 rounded-xl shadow-md p-4 flex flex-col gap-6 relative&quot;]/div[@class=&quot;flex gap-3 justify-between&quot;]/div[@class=&quot;w-2/6 flex self-end justify-end gap-3&quot;]/button[@class=&quot;bg-red-600 text-white text-xs py-1 px-6 rounded-md tracking-wide&quot;]</value>
      <webElementGuid>5d87e1c4-0adc-4270-8118-21511e58666a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7765e419-707d-4f3c-878d-4710cc0d55c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>2dee024b-bf68-48f2-86c7-12caca20dc9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
