<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reservation Created</name>
   <tag></tag>
   <elementGuidId>f00e1e97-963d-4923-957b-8b35bdc9f58b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>081cc5cb-2b23-4215-be80-0de3f6b6e724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>02e64a12-6b1f-4df3-9252-0fd25b332434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-in</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2870edf6-8b47-4483-9495-9ceb59e5ec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast Toastify__toast-theme--light Toastify__toast--default</value>
      <webElementGuid>99e0ab24-e484-425c-b7fd-1e254507fc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservation Created!</value>
      <webElementGuid>8c3142ca-e3d8-4efa-bcf9-e0d38a0f039f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)</value>
      <webElementGuid>1d9e5440-9884-402b-9303-1d1bdcdb100e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1']</value>
      <webElementGuid>82022a49-421b-4df0-9d25-1b7619c0f9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>4b813849-9cba-49ae-889c-6f0556c33209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1' and (text() = 'Reservation Created!' or . = 'Reservation Created!')]</value>
      <webElementGuid>eaf95211-7dce-4d0f-9e77-3bd901b464c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
