<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_LogOut</name>
   <tag></tag>
   <elementGuidId>1c577f14-987d-4f4c-8b70-f8e52c49c794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/nav</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.link.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>ac2e08d9-fd42-4d23-8dbf-bf66143b9e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link cursor-pointer</value>
      <webElementGuid>2cd03883-e7ca-417f-b766-bf8efc4d25da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LogOut</value>
      <webElementGuid>8c4ae39d-5e04-4311-8f47-8397832f7b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_5f06f5&quot;]/div[@class=&quot;relative h-screen&quot;]/div[@class=&quot;flex items-center bg-violet-950 justify-between px-10 text-white py-3&quot;]/div[@class=&quot;flex w-[70%] font-[400] gap-16&quot;]/nav[@class=&quot;link cursor-pointer&quot;]</value>
      <webElementGuid>1233433e-e111-44b0-b6a7-26d3206b25e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav</value>
      <webElementGuid>062b32f8-b001-4a8b-a2c3-bc8de74a5bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'LogOut' or . = 'LogOut')]</value>
      <webElementGuid>f5ccff20-818d-4196-a252-e0ecc37d0bfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
