<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneUserRestaurant</name>
   <tag></tag>
   <elementGuidId>c57c3fdf-e3da-4d23-a8b8-66e583e51df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>da49b6bb-5cec-4c0f-9498-b7c9fd185185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>6d1f0432-52bb-494a-b752-3f2baa4e6bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>edc3b8b6-b4b4-4e73-bd9f-5916978f4ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>9cdcced7-116e-4e49-a7ae-fe43952b6907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneUserRestaurant</value>
      <webElementGuid>4caf2fc6-5314-4726-b936-af1dd872613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type&quot;)</value>
      <webElementGuid>9c9821e6-73e1-4ea2-a445-004791cd6fa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='type']</value>
      <webElementGuid>f3362ef5-bc80-4c3f-9822-f7e610c08e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6296daae-1be7-400a-b408-7bdf3ac615a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'type' and @id = 'type' and (text() = 'Select OneUserRestaurant' or . = 'Select OneUserRestaurant')]</value>
      <webElementGuid>42fec9de-e6c7-43e6-b245-939cfac6e0cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
