<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select One</name>
   <tag></tag>
   <elementGuidId>0e20a62b-b57c-4f2c-ada5-07d7ce17b436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tableId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tableId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6d5b26ff-f38a-4e8d-8d70-b70f314f62f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>72ddfa8c-5e9a-47a0-be9f-0737bee69cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>f234b56a-7048-4af5-b7c9-20892fd66dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>e1543e53-20e3-4056-ba6e-7261a54ba690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select One</value>
      <webElementGuid>e5a42112-d94f-4ff1-b46b-760de4d45313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableId&quot;)</value>
      <webElementGuid>de27a9bc-d254-493b-be4b-91e6589cd0cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tableId']</value>
      <webElementGuid>36ed8be7-789a-4000-abab-1e0c96917491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>5197536a-a24e-4170-be7e-0a681080e61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tableId' and @id = 'tableId' and (text() = 'Select One' or . = 'Select One')]</value>
      <webElementGuid>89cd6c71-624d-460e-8fe9-2e6e81c2c437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
