<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneMilano</name>
   <tag></tag>
   <elementGuidId>ed154daf-397c-4738-bb4e-0ffe6a27c134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='restaurantId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#restaurantId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cb4f5869-bb51-45aa-93d9-84938f57319f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>81e69a97-2b08-4a3b-ac5a-7839a663fead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>restaurantId</value>
      <webElementGuid>96f636f5-f96d-494d-9658-fe757fec76de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>1ee1876a-3aec-4edb-9cc0-de185b223ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneMilano</value>
      <webElementGuid>0412b1e3-a5b0-40f2-84d5-95983f4e2e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restaurantId&quot;)</value>
      <webElementGuid>467f7595-4fb3-4ba7-af3d-1cf57ccd701d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='restaurantId']</value>
      <webElementGuid>9858bfd7-1d93-4782-998f-56eeb00d8167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e9df3fc2-6cea-49b4-98b9-53be641d45d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'restaurantId' and @id = 'restaurantId' and (text() = 'Select OneMilano' or . = 'Select OneMilano')]</value>
      <webElementGuid>d0af357c-d794-4f59-bfc8-3729d4a34d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
