<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select OneOrder 1 - Capacity 1Order 2 - Capacity 2Order 3 - Capacity 3Order 4 - Capacity 4</name>
   <tag></tag>
   <elementGuidId>d505b610-879f-42c8-aecd-002c2f9f5fe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tableId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tableId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>79dd3ed4-3ded-42f2-be21-1aae8dca27ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>1d16b782-10f2-437f-bc16-cd3411daacc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableId</value>
      <webElementGuid>3e8d62c1-c692-47bc-8a90-7e73a4161850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-transparent</value>
      <webElementGuid>0beb7d7f-b666-4356-9657-2894d3d60cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4</value>
      <webElementGuid>c61ed832-246f-4d84-b3b7-dd4ed92f9bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableId&quot;)</value>
      <webElementGuid>729f2d85-8ada-437f-a0b1-d613ddcf44e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tableId']</value>
      <webElementGuid>b1a690c9-73b2-4d40-bd12-55021ae49170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>37d5bd27-42da-4530-ba82-67ba7173baca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tableId' and @id = 'tableId' and (text() = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4' or . = 'Select OneOrder: 1 - Capacity: 1Order: 2 - Capacity: 2Order: 3 - Capacity: 3Order: 4 - Capacity: 4')]</value>
      <webElementGuid>da0dc601-f0c0-4607-9386-53ad391e1749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
